"""Constants shared by virtual exFAT metadata and sector mapping."""

from __future__ import annotations

SECTOR_SIZE = 512
CLUSTER_SIZE_KIB = 64
CLUSTER_SIZE_BYTES = CLUSTER_SIZE_KIB * 1024
SECTORS_PER_CLUSTER = CLUSTER_SIZE_BYTES // SECTOR_SIZE
PARTITION_START_LBA = 2048
BOOT_REGION_SECTORS = 12
BOOT_REGION_TOTAL_SECTORS = 24
EXFAT_SIGNATURE = b"EXFAT   "
EXFAT_BOOT_SIGNATURE = b"\x55\xaa"
FAT_FREE = 0x00000000
FAT_BAD = 0xFFFFFFF7
FAT_EOC = 0xFFFFFFFF
FAT_FIRST_RESERVED = 0xFFFFFFF8
EXTENT_DATA = 0
EXTENT_ZERO = 1

# exFAT directory entry types.
ENTRY_END = 0x00
ENTRY_BITMAP = 0x81
ENTRY_UPCASE = 0x82
ENTRY_VOLUME_LABEL = 0x83
ENTRY_FILE = 0x85
ENTRY_STREAM = 0xC0
ENTRY_FILENAME = 0xC1

MAX_FILENAME_UTF16_UNITS = 255
UPCASE_TABLE_BYTES = 5836

__all__ = [
    "BOOT_REGION_SECTORS",
    "BOOT_REGION_TOTAL_SECTORS",
    "CLUSTER_SIZE_BYTES",
    "CLUSTER_SIZE_KIB",
    "ENTRY_BITMAP",
    "ENTRY_END",
    "ENTRY_FILE",
    "ENTRY_FILENAME",
    "ENTRY_STREAM",
    "ENTRY_UPCASE",
    "ENTRY_VOLUME_LABEL",
    "EXFAT_BOOT_SIGNATURE",
    "EXFAT_SIGNATURE",
    "EXTENT_DATA",
    "EXTENT_ZERO",
    "FAT_BAD",
    "FAT_EOC",
    "FAT_FIRST_RESERVED",
    "FAT_FREE",
    "MAX_FILENAME_UTF16_UNITS",
    "PARTITION_START_LBA",
    "SECTOR_SIZE",
    "SECTORS_PER_CLUSTER",
    "UPCASE_TABLE_BYTES",
]
