"""nbdkit Python API v2 plugin for RemotePFS.

Plugin keeps nbdkit-specific code thin. SectorMapper owns virtual image reads;
state is loaded from a pickle generated by the service before nbdkit starts.
"""

from __future__ import annotations

import pickle
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any

try:  # nbdkit exists only on the Linux SBC.
    import nbdkit  # type: ignore[import-not-found]
except ImportError:  # pragma: no cover - exercised through test fallback

    class _NbdkitError(Exception):
        pass

    nbdkit = SimpleNamespace(
        Error=_NbdkitError,
        CACHE_NONE=0,
        EXTENT_ZERO=1,
        FUA_NONE=0,
        THREAD_MODEL_SERIALIZE_REQUESTS=0,
    )

# Make installed flat package and source checkout both importable.
_PACKAGE_PARENT = Path(__file__).resolve().parent.parent
if str(_PACKAGE_PARENT) not in sys.path:
    sys.path.insert(0, str(_PACKAGE_PARENT))

API_VERSION = 2
image_size = 0
sector_mapper: Any = None


def config(key: str, value: str) -> None:
    """Handle nbdkit command-line plugin keys."""
    global image_size, sector_mapper
    if key == "image_size":
        image_size = int(value)
        return
    if key == "mapper_state":
        with Path(value).open("rb") as state_file:
            state = pickle.load(state_file)
        from remotepfs.sector_mapper import SectorMapper

        sector_mapper = SectorMapper.from_state(state)
        if image_size == 0:
            image_size = sector_mapper.total_bytes
        return
    raise ValueError(f"unknown configuration key: {key}")


def config_complete() -> None:
    """Validate plugin configuration after all keys are processed."""
    if image_size <= 0:
        raise ValueError("image_size must be positive")
    if sector_mapper is None:
        raise ValueError("mapper_state is required")


def get_size(h: Any = None) -> int:
    """Return virtual image size in bytes."""
    return image_size


def block_size(h: Any = None) -> tuple[int, int, int]:
    """Return minimum, preferred, and maximum I/O sizes."""
    return (512, 4096, 65536)


def is_rotational(h: Any = None) -> bool:
    """Report non-rotational virtual storage."""
    return False


def can_write(h: Any = None) -> bool:
    """Reject all writes."""
    return False


def can_trim(h: Any = None) -> bool:
    """Reject trim operations."""
    return False


def can_zero(h: Any = None) -> bool:
    """Reject write-zeroes operations."""
    return False


def can_flush(h: Any = None) -> bool:
    """No flush path exists for read-only export."""
    return False


def can_fua(h: Any = None) -> int:
    """Report no FUA support."""
    return nbdkit.FUA_NONE


def can_multi_conn(h: Any = None) -> bool:
    """Use one serialized connection."""
    return False


def can_extents(h: Any = None) -> bool:
    """Enable zero extent reporting."""
    return True


def can_cache(h: Any = None) -> int:
    """Leave caching to nbdkit cache filter."""
    return nbdkit.CACHE_NONE


def can_fast_zero(h: Any = None) -> bool:
    """Reject fast zero requests."""
    return False


def thread_model() -> int:
    """Serialize requests, matching immutable mapper state and NFS access."""
    return nbdkit.THREAD_MODEL_SERIALIZE_REQUESTS


def pread(h: Any, buf: memoryview, offset: int, flags: int) -> None:
    """Fill writable buffer with virtual image bytes."""
    if sector_mapper is None:
        raise nbdkit.Error("plugin is not configured")
    if offset < 0 or offset + len(buf) > image_size:
        raise nbdkit.Error("pread: beyond image size")
    try:
        sector_mapper.read(offset, buf)
    except OSError as exc:
        raise nbdkit.Error(repr(exc)) from exc


def extents(h: Any, count: int, offset: int, flags: int) -> list[tuple[int, int, int]]:
    """Return nbdkit extents for a requested byte range."""
    if sector_mapper is None:
        raise nbdkit.Error("plugin is not configured")
    result = []
    for start, length, is_zero in sector_mapper.extents(offset, count):
        result.append((start, length, nbdkit.EXTENT_ZERO if is_zero else 0))
    return result


def close(h: Any) -> None:
    """Close mapper file descriptors on plugin shutdown."""
    if sector_mapper is not None:
        sector_mapper.close()
